/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_TURN_TABLE_ALL_TYPES_H__
#define __RS_TURN_TABLE_ALL_TYPES_H__

#include <rs_turn_table/types/type_definitions.h>


#endif /* __RS_TURN_TABLE_ALL_TYPES_H__ */
